import {
  EmitHint,
  createPrinter,
  createSourceFile,
  NewLineKind,
  ScriptTarget,
} from "typescript";
import {
  Column,
  File,
  GenerateRequest,
  GenerateResponse,
} from "../gen/plugin/codegen_pb";

export interface SqliteOptions {
  sqlite?: {
    emit?: "functions" | "prepared";
    filename?: string;
    parameter_types?: Record<string, Record<string, string>>;
  };
}

// SQLite returns numbers for booleans and does not convert dates into JS Date.
// Unknown expressions/affinities remain unknown rather than weakening to any.
function columnType(column?: Column): string {
  const name = (column?.type?.name ?? "")
    .toLowerCase()
    .replace(/\s+/g, "")
    .replace(/\(.*/, "");
  let type = "unknown";
  if (
    /^(int|integer|tinyint|smallint|mediumint|bigint|unsignedbigint|int2|int8|real|double|doubleprecision|float|numeric|decimal|boolean|bool)$/.test(
      name,
    )
  ) {
    type = "number";
  } else if (/^(text|varchar|nvarchar|char|nchar|clob)$/.test(name)) {
    type = "string";
  } else if (name === "blob") {
    type = "Buffer";
  }

  return column?.notNull || type === "unknown" ? type : `${type} | null`;
}

// Tokenize SQL so aliases/bindings inside literals and comments stay untouched.
// Retain trivia for byte-for-byte query reconstruction apart from bind markers.
function sqlTokens(text: string): string[] {
  return (
    text.match(
      /'(?:''|[^'])*'|"(?:""|[^"])*"|`(?:``|[^`])*`|\[[^\]]*\]|--[^\r\n]*|\/\*[\s\S]*?\*\/|\?\d*|[A-Za-z_][A-Za-z0-9_]*|\s+|./g,
    ) ?? []
  );
}

export function generateSqlite(
  input: GenerateRequest,
  options: SqliteOptions,
): GenerateResponse {
  const sqlite = options.sqlite ?? {};
  const emit = sqlite.emit ?? "functions";
  if (emit !== "functions" && emit !== "prepared") {
    throw new Error(`unknown SQLite emit mode: ${emit}`);
  }

  if (
    sqlite.filename &&
    !/^[A-Za-z][A-Za-z0-9_-]*\.ts$/.test(sqlite.filename)
  ) {
    throw new Error("SQLite filename must be a simple .ts filename");
  }

  const overrides = sqlite.parameter_types ?? {};
  for (const [name, parameters] of Object.entries(overrides)) {
    const query = input.queries.find((query) => query.name === name);
    if (!query) {
      throw new Error(`parameter override references unknown query: ${name}`);
    }

    for (const [number, type] of Object.entries(parameters)) {
      if (
        !query.params.some((parameter) => String(parameter.number) === number)
      ) {
        throw new Error(
          `parameter override references unknown parameter: ${name}.${number}`,
        );
      }

      if (!/^(number|string|Buffer|unknown)( \| null)?$/.test(type)) {
        throw new Error(`invalid SQLite parameter type: ${type}`);
      }
    }
  }

  const groups = new Map<string, typeof input.queries>();
  for (const query of input.queries) {
    const filename =
      sqlite.filename ?? query.filename.replace(/\./g, "_") + ".ts";
    const queries = groups.get(filename) ?? [];
    queries.push(query);
    groups.set(filename, queries);
  }

  const files: File[] = [];
  for (const [filename, queries] of groups) {
    let output =
      "// Code generated by sqlc-gen-typescript. DO NOT EDIT.\nimport type Database from 'better-sqlite3';\n\n";
    if (emit === "prepared") {
      output +=
        "// Preserve scalar result types when pluck() is enabled.\ntype PreparedStatement<P extends unknown[], R, S> = Omit<Database.Statement<P, R>, 'pluck'> & { pluck(): Database.Statement<P, S> };\n\n";
    }

    const names = new Set<string>();
    for (const query of queries) {
      if (!/^[A-Za-z][A-Za-z0-9_]*$/.test(query.name)) {
        throw new Error(`invalid SQLite query name: ${query.name}`);
      }

      if (
        ![":exec", ":execrows", ":execlastid", ":one", ":many"].includes(
          query.cmd,
        )
      ) {
        throw new Error(`unsupported SQLite command: ${query.cmd}`);
      }

      const name = query.name[0].toLowerCase() + query.name.slice(1);
      if (names.has(name)) {
        throw new Error(`duplicate SQLite function name: ${name}`);
      }

      names.add(name);
      const prefix = query.name[0].toUpperCase() + query.name.slice(1);
      const row = `${prefix}Row`;
      const args = `${prefix}Args`;
      const params = [...query.params].sort((a, b) => a.number - b.number);
      const paramTypes = params.map(
        (param) =>
          overrides[query.name]?.[String(param.number)] ??
          columnType(param.column),
      );
      const named =
        params.length > 0 &&
        params.every((param) => param.column?.isNamedParam);
      if (!named && params.some((param) => param.column?.isNamedParam)) {
        throw new Error(
          `mixed named/positional SQLite bindings: ${query.name}`,
        );
      }

      const tokens = sqlTokens(query.text);
      const significant = tokens.filter(
        (token) => !/^\s|^--|^\/\*/.test(token),
      );
      const aliases = new Map<string, string>();
      for (let i = 0; i < significant.length - 1; i++) {
        if (significant[i].toLowerCase() === "as") {
          const token = significant[i + 1];
          const alias = /^["'`\[]/.test(token)
            ? token.slice(1, -1).replace(/(["'`])\1/g, "$1")
            : token;
          aliases.set(alias.toLowerCase(), alias);
        }
      }

      const columns = query.columns.map((column) => ({
        name: aliases.get(column.name.toLowerCase()) ?? column.name,
        type: columnType(column),
      }));
      if (
        new Set(columns.map((column) => column.name)).size !== columns.length
      ) {
        throw new Error(
          `duplicate SQLite result names require SQL aliases: ${query.name}`,
        );
      }

      if (columns.length) {
        output += `export interface ${row} {\n${columns.map((column) => `${JSON.stringify(column.name)}: ${column.type};`).join("\n")}\n}\n\n`;
      }

      // better-sqlite3 treats ?N as named bindings. Give numbered slots explicit
      // names, including repeated/out-of-order slots and intervening bare '?'.
      const numbered = tokens.some((token) => /^\?\d+$/.test(token));
      const objectBindings = named || numbered;
      const usedKeys = new Set<string>();
      const keys = params.map((param) => {
        const base = named
          ? param.column!.name
          : numbered
            ? `param${param.number}`
            : param.column?.name || `arg${param.number}`;
        let key = base;
        if (!objectBindings) {
          let suffix = 2;
          while (usedKeys.has(key)) key = `${base}_${suffix++}`;
        }

        usedKeys.add(key);
        return key;
      });
      if (new Set(keys).size !== keys.length) {
        throw new Error(`duplicate SQLite argument names: ${query.name}`);
      }

      let maxSlot = 0;
      const text = tokens
        .map((token) => {
          if (!/^\?\d*$/.test(token)) return token;
          const slot = token.length > 1 ? Number(token.slice(1)) : maxSlot + 1;
          maxSlot = Math.max(maxSlot, slot);
          const index = params.findIndex((param) => param.number === slot);
          if (index === -1) {
            throw new Error(
              `missing SQLite parameter metadata: ${query.name}.${slot}`,
            );
          }

          return objectBindings ? `@${keys[index]}` : token;
        })
        .join("");
      if (params.length && (objectBindings || emit === "functions")) {
        output += `export interface ${args} {\n${keys.map((key, index) => `${JSON.stringify(key)}: ${paramTypes[index]};`).join("\n")}\n}\n\n`;
      }

      const bindings = objectBindings
        ? `[${args}]`
        : `[${paramTypes.join(", ")}]`;
      const rowType = columns.length ? row : "unknown";
      if (emit === "functions") {
        output += `export const ${name}Query = ${JSON.stringify(text)};\n\n`;
      }

      const statement = `database.prepare<${bindings}${columns.length ? `, ${rowType}` : ""}>(${emit === "functions" ? `${name}Query` : JSON.stringify(text)})`;
      if (emit === "prepared") {
        const scalar = columns[0]?.type ?? "unknown";
        const cast =
          columns.length && scalar !== "unknown"
            ? ` as unknown as PreparedStatement<${bindings}, ${rowType}, ${scalar}>`
            : "";
        output += `export function ${name}(database: Database.Database): PreparedStatement<${bindings}, ${rowType}, ${scalar}> {\nreturn ${statement}${cast};\n}\n\n`;
        continue;
      }

      let resultType: string;
      let call: string;
      const values = objectBindings
        ? "args"
        : keys.map((key) => `args[${JSON.stringify(key)}]`).join(", ");
      switch (query.cmd) {
        case ":one":
          resultType = `${rowType} | null`;
          call = `stmt.get(${values}) ?? null`;
          break;
        case ":many":
          resultType = `${rowType}[]`;
          call = `stmt.all(${values})`;
          break;
        case ":execrows":
          resultType = "number";
          call = `stmt.run(${values}).changes`;
          break;
        case ":execlastid":
          resultType = "number | bigint";
          call = `stmt.run(${values}).lastInsertRowid`;
          break;
        default:
          resultType = "void";
          call = `stmt.run(${values})`;
      }

      output += `export function ${name}(database: Database.Database${params.length ? `, args: ${args}` : ""}): ${resultType} {\nconst stmt = ${statement};\n${query.cmd === ":exec" ? "" : "return "}${call};\n}\n\n`;
    }

    const source = createSourceFile(
      filename,
      output,
      ScriptTarget.Latest,
      true,
    );
    const printer = createPrinter({ newLine: NewLineKind.LineFeed });
    const formatted =
      source.statements
        .map((statement) =>
          printer.printNode(EmitHint.Unspecified, statement, source),
        )
        .join("\n\n") + "\n";
    files.push(
      new File({
        name: filename,
        contents: new TextEncoder().encode(formatted),
      }),
    );
  }

  return new GenerateResponse({ files });
}
