// Code generated by sqlc-gen-typescript. DO NOT EDIT.
import type Database from 'better-sqlite3';
export interface GetAuthorRow {
    "id": number;
    "name": string;
    "bio": string | null;
}
export interface GetAuthorArgs {
    "id": number;
}
export const getAuthorQuery = "SELECT id, name, bio FROM authors\nWHERE id = ? LIMIT 1";
export function getAuthor(database: Database.Database, args: GetAuthorArgs): GetAuthorRow | null {
    const stmt = database.prepare<[
        number
    ], GetAuthorRow>(getAuthorQuery);
    return stmt.get(args["id"]) ?? null;
}
export interface ListAuthorsRow {
    "id": number;
    "name": string;
    "bio": string | null;
}
export const listAuthorsQuery = "SELECT id, name, bio FROM authors\nORDER BY name";
export function listAuthors(database: Database.Database): ListAuthorsRow[] {
    const stmt = database.prepare<[
    ], ListAuthorsRow>(listAuthorsQuery);
    return stmt.all();
}
export interface CreateAuthorArgs {
    "name": string;
    "bio": string | null;
}
export const createAuthorQuery = "INSERT INTO authors (\n  name, bio\n) VALUES (\n  ?, ?\n)";
export function createAuthor(database: Database.Database, args: CreateAuthorArgs): void {
    const stmt = database.prepare<[
        string,
        string | null
    ]>(createAuthorQuery);
    stmt.run(args["name"], args["bio"]);
}
export interface DeleteAuthorArgs {
    "id": number;
}
export const deleteAuthorQuery = "DELETE FROM authors\nWHERE id = ?";
export function deleteAuthor(database: Database.Database, args: DeleteAuthorArgs): void {
    const stmt = database.prepare<[
        number
    ]>(deleteAuthorQuery);
    stmt.run(args["id"]);
}
